export const getNavigationLinks = (user: any) => [
	{ name: 'Home', href: '/', current: true, logo: 'home', hidden: false },
	{
		name: 'Users',
		href: '/users',
		current: false,
		logo: 'avatar',
		hidden: false,
		disabled: false,
	},
	{
		name: 'Books',
		href: '/books',
		current: false,
		logo: 'reader',
		hidden: false,
		disabled: false,
	},
	{
		name: 'Search',
		href: '#',
		current: false,
		logo: 'magnifying-glass',
		hidden: false,
		disabled: true,
		soon: true,
	},
	{
		name: 'Recommendations',
		href: '#',
		current: false,
		logo: 'star',
		hidden: false,
		disabled: true,
		soon: true,
	},
	{
		name: 'Swaps',
		href: '#',
		current: false,
		logo: 'person',
		hidden: false,
		disabled: true,
		soon: true,
	},
	{
		name: 'Reviews',
		href: '#',
		current: false,
		logo: 'pencil-1',
		hidden: false,
		disabled: true,
		soon: true,
	},
	{
		name: 'Location Matching',
		href: '#',
		current: false,
		logo: 'globe',
		hidden: false,
		disabled: true,
		soon: true,
	},
	{
		name: 'Environmental Impact Tracker',
		href: '#',
		current: false,
		logo: 'bar-chart',
		hidden: true,
		disabled: true,
	},
	{
		name: 'Barcode Scanner',
		href: '#',
		current: false,
		logo: 'line-height',
		hidden: true,
		disabled: true,
	},
	{
		name: 'My Community',
		href: '/community/history',
		current: false,
		logo: 'face',
		hidden: false,
		disabled: false,
		soon: true,
	},
	{
		name: 'Integrations',
		href: '#',
		current: false,
		logo: 'space-evenly-horizontally',
		hidden: true,
		disabled: true,
	},
	{
		name: 'Updates',
		href: '#',
		current: false,
		logo: 'update',
		hidden: true,
		disabled: true,
	},
	{
		name: 'Tutorials & Onboarding',
		href: '#',
		current: false,
		logo: 'question-mark-circled',
		hidden: true,
		disabled: true,
	},
	{
		name: 'Feedback',
		href: '/community/bugs',
		current: false,
		logo: 'code',
		hidden: false,
		soon: true,
	},
	{
		name: 'About Me',
		href: '/about',
		current: false,
		logo: 'avatar',
		hidden: false,
	},
];
