export const getNavigationLinks = (user: any) => [
    { name: 'Home', href: '/', current: true, logo: 'home', hidden: false },
    {
        name: 'Users',
        href: '/users',
        current: false,
        logo: 'avatar',
        hidden: false,
    },
    {
        name: 'Books',
        href: '/books',
        current: false,
        logo: 'reader',
        hidden: false,
    },
    {
        name: 'Search',
        href: '#',
        current: false,
        logo: 'magnifying-glass',
        hidden: false,
    },
    {
        name: 'Recommendations',
        href: '#',
        current: false,
        logo: 'star',
        hidden: false,
    },
    { name: 'Swaps', href: '#', current: false, logo: 'person', hidden: false },
    {
        name: 'Reviews',
        href: '#',
        current: false,
        logo: 'pencil-1',
        hidden: false,
    },
    {
        name: 'Location Matching',
        href: '#',
        current: false,
        logo: 'globe',
        hidden: false,
    },
    {
        name: 'Environmental Impact Tracker',
        href: '#',
        current: false,
        logo: 'bar-chart',
        hidden: true,
    },
    {
        name: 'Barcode Scanner',
        href: '#',
        current: false,
        logo: 'line-height',
        hidden: true,
    },
    {
        name: 'My Community',
        href: '#',
        current: false,
        logo: 'face',
        hidden: false,
    },
    {
        name: 'Integrations',
        href: '#',
        current: false,
        logo: 'space-evenly-horizontally',
        hidden: true,
    },
    {
        name: 'Updates',
        href: '#',
        current: false,
        logo: 'update',
        hidden: true,
    },
    {
        name: 'Tutorials & Onboarding',
        href: '#',
        current: false,
        logo: 'question-mark-circled',
        hidden: true,
    },
    {
        name: 'Donate',
        href: '#',
        current: false,
        logo: 'code',
        hidden: false,
    },
];