export const BOOK_STATUSES = {
	AVAILABLE: 'AVAILABLE',
	SWAPPED: 'SWAPPED',
	WISHLIST: 'WISHLIST',
};

// new, like new, very good, good, acceptable, poor
export const BOOK_CONDITIONS = {
	NEW: 'NEW',
	'LIKE-NEW': 'LIKE NEW',
	'VERY-GOOD': 'VERY GOOD',
	GOOD: 'GOOD',
	ACCEPTABLE: 'ACCEPTABLE',
	POOR: 'POOR',
};

export const GENRES = {
	FICTION: 'FICTION',
	'NON-FICTION': 'NON-FICTION',
	HISTORICAL: 'HISTORICAL',
	BIOGRAPHY: 'BIOGRAPHY',
	CLASSIC: 'CLASSIC',
	ROMANCE: 'ROMANCE',
	GRAPHIC: 'GRAPHIC',
	EDUCATIONAL: 'EDUCATIONAL',
	MYSTERY: 'MYSTERY',
	SCIENCE: 'SCIENCE',
	SPIRITUALITY: 'SPIRITUALITY',
	CODING: 'CODING',
	FANTASY: 'FANTASY',
};
